version: "3.7"

services:
  mempool-db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mempool-mysql:/var/lib/mysql
    restart: unless-stopped

  mempool-api:
    image: mempool/backend:latest
    depends_on:
      - mempool-db
      - bitcoind
      - esplora
    environment:
      MEMPOOL_BACKEND: electrum
      MEMPOOL_NETWORK: regtest
      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: bitcoinrpc
      CORE_RPC_PASSWORD: bitcoinrpc
      DATABASE_ENABLED: "true"
      DATABASE_HOST: mempool-db
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool
      ELECTRUM_HOST: esplora
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      BACKEND_HTTP_PORT: "8999"
    volumes:
      - mempool-cache:/backend/cache
    restart: unless-stopped

  mempool-web:
    image: mempool/frontend:latest
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: mempool-api
      BACKEND_MAINNET_HTTP_PORT: "8999"
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  mempool-mysql:
  mempool-cache:


